AWSTemplateFormatVersion: '2010-09-09'
Description: SDCP Fundraising Website
Parameters: {}
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      # AnalyticsConfigurations:
      #   - AnalyticsConfiguration
      #   - "..."
      BucketName: www.sdcpfundraiser.org
      # LoggingConfiguration: LoggingConfiguration
      # MetricsConfigurations:
      #   - MetricsConfiguration
      #   - "..."
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteSSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: www.sdcpfundraiser.org
      DomainValidationOptions:
        - DomainName: www.sdcpfundraiser.org
          ValidationDomain: sdcpfundraiser.org
      SubjectAlternativeNames:
        - sdcpfundraiser.org
        - sdcpfundraiser.com
        - www.sdcpfundraiser.com

  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref WebsiteBucket
        Comment: !Ref 'AWS::StackName'
        DefaultCacheBehavior:
          Compress: true
          DefaultTTL: 600
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MaxTTL: 600
          TargetOriginId: !Sub S3-${WebsiteBucket}
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins:
          - Id: !Sub S3-${WebsiteBucket}
            DomainName: !GetAtt [WebsiteBucket, DomainName]
            S3OriginConfig: {}
        PriceClass: PriceClass_100
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !Ref WebsiteSSLCertificate

  WebsiteDomain:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt [WebsiteDistribution, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2
      Comment: !Ref 'AWS::StackName'
      HostedZoneName: sdcpfundraiser.org.
      Name: www.sdcpfundraiser.org.
      Type: A
